# coding: utf-8

"""
    Lingible API

    API for translating GenZ/teen slang to English and vice versa using AWS Bedrock

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lingible_client.models.user_subscription_response import UserSubscriptionResponse

class TestUserSubscriptionResponse(unittest.TestCase):
    """UserSubscriptionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserSubscriptionResponse:
        """Test UserSubscriptionResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserSubscriptionResponse`
        """
        model = UserSubscriptionResponse()
        if include_optional:
            return UserSubscriptionResponse(
                provider = 'apple',
                transaction_id = '1000000123456789',
                status = 'active',
                start_date = '2024-12-01T00:00Z',
                end_date = '2025-12-01T00:00Z',
                created_at = '2024-12-01T00:00Z'
            )
        else:
            return UserSubscriptionResponse(
        )
        """

    def testUserSubscriptionResponse(self):
        """Test UserSubscriptionResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
