# coding: utf-8

"""
    Lingible API

    API for translating GenZ/teen slang to English and vice versa using AWS Bedrock

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lingible_client.models.quiz_session_progress import QuizSessionProgress

class TestQuizSessionProgress(unittest.TestCase):
    """QuizSessionProgress unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QuizSessionProgress:
        """Test QuizSessionProgress
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QuizSessionProgress`
        """
        model = QuizSessionProgress()
        if include_optional:
            return QuizSessionProgress(
                questions_answered = 5,
                correct_count = 4,
                total_score = 35.5,
                accuracy = 0.8,
                time_spent_seconds = 245.3
            )
        else:
            return QuizSessionProgress(
                questions_answered = 5,
                correct_count = 4,
                total_score = 35.5,
                accuracy = 0.8,
                time_spent_seconds = 245.3,
        )
        """

    def testQuizSessionProgress(self):
        """Test QuizSessionProgress"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
