# coding: utf-8

"""
    Lingible API

    API for translating GenZ/teen slang to English and vice versa using AWS Bedrock

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lingible_client.models.upgrade_response import UpgradeResponse

class TestUpgradeResponse(unittest.TestCase):
    """UpgradeResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpgradeResponse:
        """Test UpgradeResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpgradeResponse`
        """
        model = UpgradeResponse()
        if include_optional:
            return UpgradeResponse(
                success = True,
                tier = 'premium',
                expires_at = '2025-01-19T10:30Z'
            )
        else:
            return UpgradeResponse(
        )
        """

    def testUpgradeResponse(self):
        """Test UpgradeResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
