# coding: utf-8

"""
    Lingible API

    API for translating GenZ/teen slang to English and vice versa using AWS Bedrock

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lingible_client.api.slang_api import SlangApi


class TestSlangApi(unittest.TestCase):
    """SlangApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SlangApi()

    def tearDown(self) -> None:
        pass

    def test_slang_submit_post(self) -> None:
        """Test case for slang_submit_post

        Submit new slang term
        """
        pass


if __name__ == '__main__':
    unittest.main()
