# coding: utf-8

"""
    Lingible API

    API for translating GenZ/teen slang to English and vice versa using AWS Bedrock

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lingible_client.models.quiz_submission_request import QuizSubmissionRequest

class TestQuizSubmissionRequest(unittest.TestCase):
    """QuizSubmissionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QuizSubmissionRequest:
        """Test QuizSubmissionRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QuizSubmissionRequest`
        """
        model = QuizSubmissionRequest()
        if include_optional:
            return QuizSubmissionRequest(
                challenge_id = 'quiz_a1b2c3d4e5f6g7h8',
                answers = [
                    lingible_client.models.quiz_answer.QuizAnswer(
                        question_id = 'q_a1b2c3d4e5f6',
                        selected = 'a', )
                    ],
                time_taken_seconds = 45
            )
        else:
            return QuizSubmissionRequest(
                challenge_id = 'quiz_a1b2c3d4e5f6g7h8',
                answers = [
                    lingible_client.models.quiz_answer.QuizAnswer(
                        question_id = 'q_a1b2c3d4e5f6',
                        selected = 'a', )
                    ],
                time_taken_seconds = 45,
        )
        """

    def testQuizSubmissionRequest(self):
        """Test QuizSubmissionRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
