# coding: utf-8

"""
    Lingible API

    API for translating GenZ/teen slang to English and vice versa using AWS Bedrock

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lingible_client.models.quiz_history import QuizHistory

class TestQuizHistory(unittest.TestCase):
    """QuizHistory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QuizHistory:
        """Test QuizHistory
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QuizHistory`
        """
        model = QuizHistory()
        if include_optional:
            return QuizHistory(
                user_id = 'user_123456789',
                total_quizzes = 25,
                average_score = 87.5,
                best_score = 110,
                total_correct = 225,
                total_questions = 250,
                accuracy_rate = 0.9,
                quizzes_today = 2,
                can_take_quiz = True,
                reason = 'Daily limit of 3 quizzes reached. Upgrade to Premium for unlimited quizzes!'
            )
        else:
            return QuizHistory(
                user_id = 'user_123456789',
                total_quizzes = 25,
                average_score = 87.5,
                best_score = 110,
                total_correct = 225,
                total_questions = 250,
                accuracy_rate = 0.9,
                quizzes_today = 2,
                can_take_quiz = True,
        )
        """

    def testQuizHistory(self):
        """Test QuizHistory"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
