# coding: utf-8

"""
    Lingible API

    API for translating GenZ/teen slang to English and vice versa using AWS Bedrock

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lingible_client.models.translation_history import TranslationHistory

class TestTranslationHistory(unittest.TestCase):
    """TranslationHistory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TranslationHistory:
        """Test TranslationHistory
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TranslationHistory`
        """
        model = TranslationHistory()
        if include_optional:
            return TranslationHistory(
                translation_id = 'trans_123456789',
                user_id = 'user_123456789',
                original_text = 'Hello, how are you doing today?',
                translated_text = 'Yo, what's good fam?',
                direction = 'english_to_genz',
                confidence_score = 0.95,
                created_at = '2024-12-19T10:30Z',
                model_used = 'anthropic.claude-3-haiku-20240307-v1:0'
            )
        else:
            return TranslationHistory(
                translation_id = 'trans_123456789',
                original_text = 'Hello, how are you doing today?',
                translated_text = 'Yo, what's good fam?',
                direction = 'english_to_genz',
                created_at = '2024-12-19T10:30Z',
        )
        """

    def testTranslationHistory(self):
        """Test TranslationHistory"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
