# coding: utf-8

"""
    Lingible API

    API for translating GenZ/teen slang to English and vice versa using AWS Bedrock

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lingible_client.api.user_api import UserApi


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UserApi()

    def tearDown(self) -> None:
        pass

    def test_v1_user_profile_get(self) -> None:
        """Test case for v1_user_profile_get

        Get user profile
        """
        pass

    def test_v1_user_upgrade_post(self) -> None:
        """Test case for v1_user_upgrade_post

        Upgrade user subscription
        """
        pass

    def test_v1_user_usage_get(self) -> None:
        """Test case for v1_user_usage_get

        Get usage statistics
        """
        pass


if __name__ == '__main__':
    unittest.main()
