# coding: utf-8

"""
    Lingible API

    API for translating GenZ/teen slang to English and vice versa using AWS Bedrock

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lingible_client.api.admin_api import AdminApi


class TestAdminApi(unittest.TestCase):
    """AdminApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AdminApi()

    def tearDown(self) -> None:
        pass

    def test_slang_admin_approve_submission_id_post(self) -> None:
        """Test case for slang_admin_approve_submission_id_post

        Admin approve slang submission
        """
        pass

    def test_slang_admin_reject_submission_id_post(self) -> None:
        """Test case for slang_admin_reject_submission_id_post

        Admin reject slang submission
        """
        pass


if __name__ == '__main__':
    unittest.main()
