# coding: utf-8

"""
    Lingible API

    API for translating GenZ/teen slang to English and vice versa using AWS Bedrock

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lingible_client.models.usage_response import UsageResponse

class TestUsageResponse(unittest.TestCase):
    """UsageResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UsageResponse:
        """Test UsageResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UsageResponse`
        """
        model = UsageResponse()
        if include_optional:
            return UsageResponse(
                current_period = lingible_client.models.usage_period.UsagePeriod(
                    translations_used = 7,
                    translations_limit = 10,
                    period_start = '2024-12-19T00:00Z',
                    period_end = '2024-12-19T23:59:59Z', ),
                limits = lingible_client.models.usage_limits.UsageLimits(
                    free_tier = 10,
                    premium_tier = 100, )
            )
        else:
            return UsageResponse(
        )
        """

    def testUsageResponse(self):
        """Test UsageResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
