# coding: utf-8

"""
    Lingible API

    API for translating GenZ/teen slang to English and vice versa using AWS Bedrock

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lingible_client.models.quiz_challenge import QuizChallenge

class TestQuizChallenge(unittest.TestCase):
    """QuizChallenge unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QuizChallenge:
        """Test QuizChallenge
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QuizChallenge`
        """
        model = QuizChallenge()
        if include_optional:
            return QuizChallenge(
                challenge_id = 'quiz_a1b2c3d4e5f6g7h8',
                challenge_type = 'multiple_choice',
                difficulty = 'beginner',
                time_limit_seconds = 60,
                questions = [
                    lingible_client.models.quiz_question.QuizQuestion(
                        question_id = 'q_a1b2c3d4e5f6',
                        slang_term = 'bussin',
                        question_text = 'What does 'bussin' mean?',
                        options = [
                            lingible_client.models.quiz_option.QuizOption(
                                id = 'a',
                                text = 'Really good, amazing, excellent',
                                is_correct = True, )
                            ],
                        context_hint = 'This pizza is bussin!',
                        explanation = '', )
                    ],
                scoring = lingible_client.models.quiz_challenge_scoring.QuizChallenge_scoring(
                    points_per_correct = 10,
                    time_bonus = True, ),
                expires_at = '2024-12-19T11:30Z'
            )
        else:
            return QuizChallenge(
                challenge_id = 'quiz_a1b2c3d4e5f6g7h8',
                challenge_type = 'multiple_choice',
                difficulty = 'beginner',
                time_limit_seconds = 60,
                questions = [
                    lingible_client.models.quiz_question.QuizQuestion(
                        question_id = 'q_a1b2c3d4e5f6',
                        slang_term = 'bussin',
                        question_text = 'What does 'bussin' mean?',
                        options = [
                            lingible_client.models.quiz_option.QuizOption(
                                id = 'a',
                                text = 'Really good, amazing, excellent',
                                is_correct = True, )
                            ],
                        context_hint = 'This pizza is bussin!',
                        explanation = '', )
                    ],
                scoring = lingible_client.models.quiz_challenge_scoring.QuizChallenge_scoring(
                    points_per_correct = 10,
                    time_bonus = True, ),
                expires_at = '2024-12-19T11:30Z',
        )
        """

    def testQuizChallenge(self):
        """Test QuizChallenge"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
