# coding: utf-8

"""
    Lingible API

    API for translating GenZ/teen slang to English and vice versa using AWS Bedrock

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lingible_client.models.account_deletion_response import AccountDeletionResponse

class TestAccountDeletionResponse(unittest.TestCase):
    """AccountDeletionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AccountDeletionResponse:
        """Test AccountDeletionResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AccountDeletionResponse`
        """
        model = AccountDeletionResponse()
        if include_optional:
            return AccountDeletionResponse(
                success = True,
                message = 'Your account and all associated data have been permanently deleted.',
                deleted_at = '2024-12-19T10:30Z',
                cleanup_summary = lingible_client.models.account_deletion_response_cleanup_summary.AccountDeletionResponse_cleanup_summary(
                    translations_deleted = 25,
                    subscription_cancelled = True,
                    data_retention_period = '30 days for billing records', )
            )
        else:
            return AccountDeletionResponse(
        )
        """

    def testAccountDeletionResponse(self):
        """Test AccountDeletionResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
