# coding: utf-8

"""
    Lingible API

    API for translating GenZ/teen slang to English and vice versa using AWS Bedrock

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lingible_client.models.apple_webhook_request import AppleWebhookRequest

class TestAppleWebhookRequest(unittest.TestCase):
    """AppleWebhookRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppleWebhookRequest:
        """Test AppleWebhookRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppleWebhookRequest`
        """
        model = AppleWebhookRequest()
        if include_optional:
            return AppleWebhookRequest(
                notification_type = 'INITIAL_BUY',
                transaction_id = '1000000123456789',
                receipt_data = 'ewoJInNpZ25hdHVyZSIgPSAiQWh...'
            )
        else:
            return AppleWebhookRequest(
                notification_type = 'INITIAL_BUY',
                transaction_id = '1000000123456789',
                receipt_data = 'ewoJInNpZ25hdHVyZSIgPSAiQWh...',
        )
        """

    def testAppleWebhookRequest(self):
        """Test AppleWebhookRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
