# coding: utf-8

"""
    Lingible API

    API for translating GenZ/teen slang to English and vice versa using AWS Bedrock

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lingible_client.models.translation_history_response import TranslationHistoryResponse

class TestTranslationHistoryResponse(unittest.TestCase):
    """TranslationHistoryResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TranslationHistoryResponse:
        """Test TranslationHistoryResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TranslationHistoryResponse`
        """
        model = TranslationHistoryResponse()
        if include_optional:
            return TranslationHistoryResponse(
                translations = [
                    lingible_client.models.translation_response.TranslationResponse(
                        translation_id = 'trans_123456789',
                        original_text = 'That's cap fr fr',
                        translated_text = 'That's not true, for real for real',
                        direction = 'english_to_genz',
                        confidence_score = 0.95,
                        created_at = '2024-12-19T10:30Z',
                        processing_time_ms = 1250,
                        model_used = 'anthropic.claude-3-5-sonnet-20241022-v2:0', )
                    ],
                pagination = lingible_client.models.pagination_info.PaginationInfo(
                    total = 150,
                    limit = 20,
                    offset = 0,
                    has_more = True, )
            )
        else:
            return TranslationHistoryResponse(
        )
        """

    def testTranslationHistoryResponse(self):
        """Test TranslationHistoryResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
