# coding: utf-8

"""
    Lingible API

    API for translating GenZ/teen slang to English and vice versa using AWS Bedrock

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lingible_client.api.translation_api import TranslationApi


class TestTranslationApi(unittest.TestCase):
    """TranslationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TranslationApi()

    def tearDown(self) -> None:
        pass

    def test_v1_translate_post(self) -> None:
        """Test case for v1_translate_post

        Translate teen slang
        """
        pass

    def test_v1_translations_delete(self) -> None:
        """Test case for v1_translations_delete

        Clear all slang translations
        """
        pass

    def test_v1_translations_get(self) -> None:
        """Test case for v1_translations_get

        Get slang translation history
        """
        pass

    def test_v1_translations_id_delete(self) -> None:
        """Test case for v1_translations_id_delete

        Delete specific slang translation
        """
        pass


if __name__ == '__main__':
    unittest.main()
