# coding: utf-8

"""
    Lingible API

    API for translating GenZ/teen slang to English and vice versa using AWS Bedrock

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lingible_client.models.slang_submission import SlangSubmission

class TestSlangSubmission(unittest.TestCase):
    """SlangSubmission unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SlangSubmission:
        """Test SlangSubmission
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SlangSubmission`
        """
        model = SlangSubmission()
        if include_optional:
            return SlangSubmission(
                submission_id = 'sub_a1b2c3d4e5f6g7h8',
                user_id = 'user_123456789',
                slang_term = 'bussin',
                meaning = 'Really good, amazing, excellent',
                example_usage = 'This pizza is bussin!',
                context = 'manual',
                original_translation_id = '',
                status = 'pending',
                llm_validation_status = 'validated',
                llm_confidence_score = 0.75,
                approval_type = 'llm_auto',
                upvotes = 5,
                created_at = '2024-12-19T10:30Z',
                reviewed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                reviewed_by = '',
                approved_by = ''
            )
        else:
            return SlangSubmission(
                submission_id = 'sub_a1b2c3d4e5f6g7h8',
                user_id = 'user_123456789',
                slang_term = 'bussin',
                meaning = 'Really good, amazing, excellent',
                context = 'manual',
                status = 'pending',
                llm_validation_status = 'validated',
                upvotes = 5,
                created_at = '2024-12-19T10:30Z',
        )
        """

    def testSlangSubmission(self):
        """Test SlangSubmission"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
