# coding: utf-8

"""
    Lingible API

    API for translating GenZ/teen slang to English and vice versa using AWS Bedrock

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lingible_client.models.slang_submission_response import SlangSubmissionResponse

class TestSlangSubmissionResponse(unittest.TestCase):
    """SlangSubmissionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SlangSubmissionResponse:
        """Test SlangSubmissionResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SlangSubmissionResponse`
        """
        model = SlangSubmissionResponse()
        if include_optional:
            return SlangSubmissionResponse(
                submission_id = 'sub_a1b2c3d4e5f6g7h8',
                status = 'pending',
                message = 'Thanks for the submission! We'll review it soon. No cap, we appreciate your help!',
                created_at = '2024-12-19T10:30Z'
            )
        else:
            return SlangSubmissionResponse(
                submission_id = 'sub_a1b2c3d4e5f6g7h8',
                status = 'pending',
                message = 'Thanks for the submission! We'll review it soon. No cap, we appreciate your help!',
                created_at = '2024-12-19T10:30Z',
        )
        """

    def testSlangSubmissionResponse(self):
        """Test SlangSubmissionResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
