# coding: utf-8

"""
    Lingible API

    API for translating GenZ/teen slang to English and vice versa using AWS Bedrock

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lingible_client.models.challenge_type import ChallengeType

class TestChallengeType(unittest.TestCase):
    """ChallengeType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChallengeType(self):
        """Test ChallengeType"""
        # inst = ChallengeType()

if __name__ == '__main__':
    unittest.main()
