# coding: utf-8

"""
    Lingible API

    API for translating GenZ/teen slang to English and vice versa using AWS Bedrock

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lingible_client.models.quiz_answer_response import QuizAnswerResponse

class TestQuizAnswerResponse(unittest.TestCase):
    """QuizAnswerResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QuizAnswerResponse:
        """Test QuizAnswerResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QuizAnswerResponse`
        """
        model = QuizAnswerResponse()
        if include_optional:
            return QuizAnswerResponse(
                is_correct = True,
                points_earned = 8.5,
                explanation = 'Really good',
                running_stats = lingible_client.models.quiz_session_progress.QuizSessionProgress(
                    questions_answered = 5,
                    correct_count = 4,
                    total_score = 35.5,
                    accuracy = 0.8,
                    time_spent_seconds = 245.3, )
            )
        else:
            return QuizAnswerResponse(
                is_correct = True,
                points_earned = 8.5,
                explanation = 'Really good',
                running_stats = lingible_client.models.quiz_session_progress.QuizSessionProgress(
                    questions_answered = 5,
                    correct_count = 4,
                    total_score = 35.5,
                    accuracy = 0.8,
                    time_spent_seconds = 245.3, ),
        )
        """

    def testQuizAnswerResponse(self):
        """Test QuizAnswerResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
