# coding: utf-8

"""
    Lingible API

    API for translating GenZ/teen slang to English and vice versa using AWS Bedrock

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lingible_client.models.trending_list_response import TrendingListResponse

class TestTrendingListResponse(unittest.TestCase):
    """TrendingListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TrendingListResponse:
        """Test TrendingListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TrendingListResponse`
        """
        model = TrendingListResponse()
        if include_optional:
            return TrendingListResponse(
                terms = [
                    lingible_client.models.trending_term_response.TrendingTermResponse(
                        term = 'no cap',
                        definition = 'No lie, for real, I'm telling the truth',
                        category = 'slang',
                        popularity_score = 85.5,
                        search_count = 1250,
                        translation_count = 890,
                        first_seen = '2024-12-01T00:00Z',
                        last_updated = '2024-12-19T10:30Z',
                        is_active = True,
                        example_usage = 'That movie was fire, no cap!',
                        origin = 'Hip hop culture',
                        related_terms = ["fr","for real","deadass"], )
                    ],
                total_count = 150,
                last_updated = '2024-12-19T10:30Z',
                category_filter = 'slang'
            )
        else:
            return TrendingListResponse(
        )
        """

    def testTrendingListResponse(self):
        """Test TrendingListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
