# coding: utf-8

"""
    Lingible API

    API for translating GenZ/teen slang to English and vice versa using AWS Bedrock

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lingible_client.models.user_profile_response import UserProfileResponse

class TestUserProfileResponse(unittest.TestCase):
    """UserProfileResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserProfileResponse:
        """Test UserProfileResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserProfileResponse`
        """
        model = UserProfileResponse()
        if include_optional:
            return UserProfileResponse(
                user_id = 'user_123456789',
                email = 'user@example.com',
                tier = 'free',
                status = 'active',
                created_at = '2024-12-01T00:00Z',
                updated_at = '2024-12-19T10:30Z'
            )
        else:
            return UserProfileResponse(
        )
        """

    def testUserProfileResponse(self):
        """Test UserProfileResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
