# coding: utf-8

"""
    Lingible API

    API for translating GenZ/teen slang to English and vice versa using AWS Bedrock

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lingible_client.models.account_deletion_response_cleanup_summary import AccountDeletionResponseCleanupSummary

class TestAccountDeletionResponseCleanupSummary(unittest.TestCase):
    """AccountDeletionResponseCleanupSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AccountDeletionResponseCleanupSummary:
        """Test AccountDeletionResponseCleanupSummary
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AccountDeletionResponseCleanupSummary`
        """
        model = AccountDeletionResponseCleanupSummary()
        if include_optional:
            return AccountDeletionResponseCleanupSummary(
                translations_deleted = 25,
                subscription_cancelled = True,
                data_retention_period = '30 days for billing records'
            )
        else:
            return AccountDeletionResponseCleanupSummary(
        )
        """

    def testAccountDeletionResponseCleanupSummary(self):
        """Test AccountDeletionResponseCleanupSummary"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
