# coding: utf-8

"""
    Lingible API

    API for translating GenZ/teen slang to English and vice versa using AWS Bedrock

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lingible_client.api.quiz_api import QuizApi


class TestQuizApi(unittest.TestCase):
    """QuizApi unit test stubs"""

    def setUp(self) -> None:
        self.api = QuizApi()

    def tearDown(self) -> None:
        pass

    def test_quiz_challenge_get(self) -> None:
        """Test case for quiz_challenge_get

        Get a quiz challenge
        """
        pass

    def test_quiz_history_get(self) -> None:
        """Test case for quiz_history_get

        Get quiz history and eligibility
        """
        pass

    def test_quiz_submit_post(self) -> None:
        """Test case for quiz_submit_post

        Submit quiz answers
        """
        pass


if __name__ == '__main__':
    unittest.main()
