# coding: utf-8

"""
    Lingible API

    API for translating GenZ/teen slang to English and vice versa using AWS Bedrock

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lingible_client.models.receipt_validation_response import ReceiptValidationResponse

class TestReceiptValidationResponse(unittest.TestCase):
    """ReceiptValidationResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReceiptValidationResponse:
        """Test ReceiptValidationResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReceiptValidationResponse`
        """
        model = ReceiptValidationResponse()
        if include_optional:
            return ReceiptValidationResponse(
                is_valid = True,
                status = 'valid',
                transaction_id = '1000000123456789',
                product_id = 'com.lingible.premium.monthly',
                purchase_date = '2024-12-01T00:00Z',
                expiration_date = '2025-01-01T00:00Z',
                environment = 'production',
                error_message = 'Receipt validation failed',
                retry_after = 60
            )
        else:
            return ReceiptValidationResponse(
        )
        """

    def testReceiptValidationResponse(self):
        """Test ReceiptValidationResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
