# coding: utf-8

"""
    Lingible API

    API for translating GenZ/teen slang to English and vice versa using AWS Bedrock

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lingible_client.api.trending_api import TrendingApi


class TestTrendingApi(unittest.TestCase):
    """TrendingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TrendingApi()

    def tearDown(self) -> None:
        pass

    def test_trending_get(self) -> None:
        """Test case for trending_get

        Get trending GenZ slang terms
        """
        pass


if __name__ == '__main__':
    unittest.main()
