"""Initialize quiz wrong answer pools for all quiz categories."""

import json
import sys
import os
from pathlib import Path
from typing import List, Set

# Add parent directory to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent.parent))

# Set environment for local execution if not set
if not os.environ.get("ENVIRONMENT"):
    os.environ["ENVIRONMENT"] = "test"

from models.quiz import QuizCategory  # noqa: E402
from repositories.lexicon_repository import LexiconRepository  # noqa: E402
from utils.smart_logger import logger  # noqa: E402


# Curated wrong answer pools per category (50-100 options each)
WRONG_ANSWER_POOLS = {
    QuizCategory.APPROVAL: [
        "Bad",
        "Terrible",
        "Awful",
        "Horrible",
        "Poor",
        "Worst",
        "Disgusting",
        "Okay",
        "Average",
        "Mediocre",
        "Decent",
        "Fine",
        "Acceptable",
        "Alright",
        "Amazing",
        "Excellent",
        "Perfect",
        "Outstanding",
        "Incredible",
        "Wonderful",
        "Good",
        "Great",
        "Nice",
        "Cool",
        "Solid",
        "Alright",
        "Fine",
        "Okay",
        "Beautiful",
        "Stunning",
        "Gorgeous",
        "Pretty",
        "Lovely",
        "Cute",
        "Adorable",
        "Incredible",
        "Unbelievable",
        "Extraordinary",
        "Remarkable",
        "Impressive",
        "Satisfying",
        "Pleasant",
        "Enjoyable",
        "Delightful",
        "Charming",
        "Attractive",
        "Successful",
        "Effective",
        "Efficient",
        "Productive",
        "Valuable",
        "Useful",
        "Positive",
        "Optimistic",
        "Hopeful",
        "Encouraging",
        "Inspiring",
        "Motivating",
        "Clean",
        "Fresh",
        "New",
        "Modern",
        "Updated",
        "Improved",
        "Enhanced",
        "Famous",
        "Popular",
        "Well-known",
        "Renowned",
        "Celebrated",
        "Recognized",
        "Healthy",
        "Strong",
        "Powerful",
        "Robust",
        "Sturdy",
        "Durable",
        "Reliable",
    ],
    QuizCategory.DISAPPROVAL: [
        "Good",
        "Great",
        "Excellent",
        "Perfect",
        "Amazing",
        "Wonderful",
        "Outstanding",
        "Okay",
        "Average",
        "Mediocre",
        "Decent",
        "Fine",
        "Acceptable",
        "Alright",
        "Terrible",
        "Awful",
        "Horrible",
        "Disgusting",
        "Revolting",
        "Nauseating",
        "Bad",
        "Poor",
        "Inferior",
        "Substandard",
        "Unacceptable",
        "Unsatisfactory",
        "Ugly",
        "Unattractive",
        "Plain",
        "Boring",
        "Dull",
        "Uninteresting",
        "Lifeless",
        "Weak",
        "Fragile",
        "Brittle",
        "Delicate",
        "Unstable",
        "Unreliable",
        "Faulty",
        "Slow",
        "Lazy",
        "Sluggish",
        "Inactive",
        "Lethargic",
        "Tired",
        "Exhausted",
        "Sad",
        "Depressed",
        "Unhappy",
        "Miserable",
        "Gloomy",
        "Dismal",
        "Hopeless",
        "Angry",
        "Frustrated",
        "Irritated",
        "Annoyed",
        "Upset",
        "Mad",
        "Furious",
        "Confused",
        "Lost",
        "Bewildered",
        "Perplexed",
        "Puzzled",
        "Uncertain",
        "Unclear",
        "Stupid",
        "Foolish",
        "Silly",
        "Ridiculous",
        "Absurd",
        "Nonsensical",
        "Pointless",
        "Boring",
        "Dull",
        "Tedious",
        "Monotonous",
        "Repetitive",
        "Tiresome",
        "Weary",
    ],
    QuizCategory.EMOTION: [
        "Happy",
        "Joyful",
        "Cheerful",
        "Delighted",
        "Pleased",
        "Content",
        "Satisfied",
        "Sad",
        "Depressed",
        "Unhappy",
        "Miserable",
        "Gloomy",
        "Melancholy",
        "Sorrowful",
        "Angry",
        "Furious",
        "Rage",
        "Irritated",
        "Annoyed",
        "Upset",
        "Mad",
        "Frustrated",
        "Excited",
        "Thrilled",
        "Eager",
        "Enthusiastic",
        "Pumped",
        "Amped",
        "Hyped",
        "Calm",
        "Peaceful",
        "Relaxed",
        "Serene",
        "Tranquil",
        "Composed",
        "Collected",
        "Anxious",
        "Nervous",
        "Worried",
        "Stressed",
        "Tense",
        "Uneasy",
        "Apprehensive",
        "Surprised",
        "Shocked",
        "Astonished",
        "Amazed",
        "Stunned",
        "Startled",
        "Bewildered",
        "Confused",
        "Baffled",
        "Perplexed",
        "Puzzled",
        "Uncertain",
        "Lost",
        "Bewildered",
        "Tired",
        "Exhausted",
        "Weary",
        "Fatigued",
        "Drained",
        "Worn out",
        "Spent",
        "Proud",
        "Confident",
        "Assured",
        "Self-assured",
        "Bold",
        "Brave",
        "Courageous",
        "Embarrassed",
        "Ashamed",
        "Humiliated",
        "Self-conscious",
        "Awkward",
        "Uncomfortable",
    ],
    QuizCategory.FOOD: [
        "Delicious",
        "Tasty",
        "Yummy",
        "Scrumptious",
        "Delectable",
        "Savory",
        "Appetizing",
        "Disgusting",
        "Revolting",
        "Nauseating",
        "Repulsive",
        "Off-putting",
        "Unappetizing",
        "Spicy",
        "Hot",
        "Fiery",
        "Pungent",
        "Sharp",
        "Peppery",
        "Zesty",
        "Sweet",
        "Sugary",
        "Honeyed",
        "Candied",
        "Dessert-like",
        "Sugar-filled",
        "Syrupy",
        "Sour",
        "Tart",
        "Bitter",
        "Acidic",
        "Tangy",
        "Puckering",
        "Vinegary",
        "Bland",
        "Tasteless",
        "Flavorless",
        "Plain",
        "Unseasoned",
        "Boring",
        "Dull",
        "Salty",
        "Briny",
        "Brackish",
        "Salted",
        "Seasoned",
        "Salted down",
        "Over-salted",
        "Fresh",
        "Crisp",
        "Raw",
        "Uncooked",
        "Natural",
        "Untreated",
        "Unprocessed",
        "Cooked",
        "Roasted",
        "Grilled",
        "Fried",
        "Baked",
        "Steamed",
        "Boiled",
        "Cold",
        "Frozen",
        "Chilled",
        "Icy",
        "Refrigerated",
        "Cool",
        "Frosty",
        "Hot",
        "Warm",
        "Steaming",
        "Sizzling",
        "Boiling",
        "Piping hot",
        "Scalding",
        "Large",
        "Huge",
        "Massive",
        "Giant",
        "Oversized",
        "Big",
        "Enormous",
        "Small",
        "Tiny",
        "Mini",
        "Petite",
        "Little",
        "Bite-sized",
        "Compact",
    ],
    QuizCategory.APPEARANCE: [
        "Beautiful",
        "Gorgeous",
        "Stunning",
        "Pretty",
        "Attractive",
        "Lovely",
        "Cute",
        "Ugly",
        "Unattractive",
        "Plain",
        "Homely",
        "Unappealing",
        "Repulsive",
        "Grotesque",
        "Tall",
        "Short",
        "Average height",
        "Petite",
        "Giant",
        "Tiny",
        "Large",
        "Thin",
        "Skinny",
        "Slim",
        "Slender",
        "Lean",
        "Slight",
        "Narrow",
        "Fat",
        "Thick",
        "Heavy",
        "Large",
        "Bulky",
        "Plump",
        "Overweight",
        "Young",
        "Old",
        "Aged",
        "Elderly",
        "Mature",
        "Vintage",
        "Ancient",
        "New",
        "Fresh",
        "Modern",
        "Contemporary",
        "Current",
        "Latest",
        "Recent",
        "Clean",
        "Dirty",
        "Messy",
        "Unkempt",
        "Disheveled",
        "Sloppy",
        "Untidy",
        "Colorful",
        "Dull",
        "Plain",
        "Bright",
        "Dark",
        "Vibrant",
        "Muted",
        "Fashionable",
        "Stylish",
        "Trendy",
        "Outdated",
        "Old-fashioned",
        "Classic",
        "Modern",
        "Elegant",
        "Refined",
        "Sophisticated",
        "Classy",
        "Polished",
        "Refined",
        "Graceful",
    ],
    QuizCategory.SOCIAL: [
        "Popular",
        "Famous",
        "Well-known",
        "Recognized",
        "Celebrated",
        "Renowned",
        "Notable",
        "Unpopular",
        "Unknown",
        "Obscure",
        "Unrecognized",
        "Forgotten",
        "Ignored",
        "Overlooked",
        "Friendly",
        "Social",
        "Outgoing",
        "Extroverted",
        "Approachable",
        "Welcoming",
        "Warm",
        "Shy",
        "Introverted",
        "Quiet",
        "Reserved",
        "Withdrawn",
        "Reclusive",
        "Isolated",
        "Fun",
        "Entertaining",
        "Enjoyable",
        "Pleasant",
        "Amusing",
        "Delightful",
        "Pleasurable",
        "Boring",
        "Dull",
        "Tedious",
        "Monotonous",
        "Repetitive",
        "Tiresome",
        "Uninteresting",
        "Active",
        "Energetic",
        "Dynamic",
        "Vibrant",
        "Lively",
        "Animated",
        "Spirited",
        "Inactive",
        "Lazy",
        "Sluggish",
        "Lethargic",
        "Tired",
        "Weary",
        "Exhausted",
        "Trendy",
        "Fashionable",
        "Stylish",
        "Cool",
        "Hip",
        "Modern",
        "Contemporary",
        "Old-fashioned",
        "Outdated",
        "Unfashionable",
        "Dated",
        "Antique",
        "Vintage",
        "Classic",
        "Inclusive",
        "Welcoming",
        "Open",
        "Accepting",
        "Tolerant",
        "Diverse",
        "Mixed",
        "Exclusive",
        "Elite",
        "Selective",
        "Restricted",
        "Limited",
        "Narrow",
        "Confined",
    ],
    QuizCategory.AUTHENTICITY: [
        "Real",
        "Genuine",
        "Authentic",
        "True",
        "Legitimate",
        "Valid",
        "Actual",
        "Fake",
        "False",
        "Artificial",
        "Phony",
        "Imitation",
        "Counterfeit",
        "Bogus",
        "Honest",
        "Truthful",
        "Sincere",
        "Candid",
        "Straightforward",
        "Direct",
        "Open",
        "Dishonest",
        "Deceitful",
        "Lying",
        "False",
        "Misleading",
        "Untruthful",
        "Deceptive",
        "Original",
        "Unique",
        "One-of-a-kind",
        "Distinctive",
        "Special",
        "Individual",
        "Rare",
        "Copied",
        "Imitated",
        "Replicated",
        "Duplicated",
        "Cloned",
        "Reproduced",
        "Fake",
        "Sincere",
        "Genuine",
        "Heartfelt",
        "Earnest",
        "True",
        "Real",
        "Authentic",
        "Insincere",
        "Fake",
        "Phony",
        "Pretend",
        "False",
        "Artificial",
        "Superficial",
        "Trustworthy",
        "Reliable",
        "Dependable",
        "Credible",
        "Believable",
        "Honest",
        "True",
        "Untrustworthy",
        "Unreliable",
        "Doubtful",
        "Suspicious",
        "Questionable",
        "Sketchy",
        "Natural",
        "Organic",
        "Pure",
        "Unadulterated",
        "Untainted",
        "Unmodified",
        "Clean",
        "Artificial",
        "Synthetic",
        "Manufactured",
        "Processed",
        "Fabricated",
        "Made-up",
    ],
    QuizCategory.INTENSITY: [
        "Extreme",
        "Intense",
        "Severe",
        "Powerful",
        "Strong",
        "Heavy",
        "Maximum",
        "Mild",
        "Gentle",
        "Light",
        "Soft",
        "Weak",
        "Minimal",
        "Subtle",
        "Fast",
        "Quick",
        "Rapid",
        "Swift",
        "Speedy",
        "Instant",
        "Immediate",
        "Slow",
        "Gradual",
        "Leisurely",
        "Unhurried",
        "Deliberate",
        "Measured",
        "Careful",
        "Loud",
        "Noisy",
        "Deafening",
        "Thunderous",
        "Booming",
        "Resounding",
        "Echoing",
        "Quiet",
        "Silent",
        "Hushed",
        "Muted",
        "Soft-spoken",
        "Whispered",
        "Gentle",
        "Huge",
        "Massive",
        "Enormous",
        "Giant",
        "Gigantic",
        "Colossal",
        "Immense",
        "Tiny",
        "Microscopic",
        "Minuscule",
        "Minute",
        "Miniature",
        "Small",
        "Little",
        "Bright",
        "Brilliant",
        "Radiant",
        "Dazzling",
        "Glowing",
        "Luminous",
        "Shining",
        "Dark",
        "Dim",
        "Dull",
        "Faded",
        "Shadowy",
        "Gloomy",
        "Murky",
        "Hot",
        "Scorching",
        "Boiling",
        "Blazing",
        "Fiery",
        "Sizzling",
        "Burning",
        "Cold",
        "Freezing",
        "Icy",
        "Frosty",
        "Chilled",
        "Cool",
        "Frigid",
    ],
    QuizCategory.GENERAL: [
        "Good",
        "Great",
        "Excellent",
        "Perfect",
        "Amazing",
        "Wonderful",
        "Outstanding",
        "Bad",
        "Terrible",
        "Awful",
        "Horrible",
        "Poor",
        "Worst",
        "Disgusting",
        "Okay",
        "Average",
        "Mediocre",
        "Decent",
        "Fine",
        "Acceptable",
        "Alright",
        "Interesting",
        "Fascinating",
        "Engaging",
        "Compelling",
        "Captivating",
        "Intriguing",
        "Boring",
        "Dull",
        "Tedious",
        "Monotonous",
        "Repetitive",
        "Tiresome",
        "Uninteresting",
        "Important",
        "Significant",
        "Crucial",
        "Vital",
        "Essential",
        "Critical",
        "Key",
        "Unimportant",
        "Insignificant",
        "Trivial",
        "Minor",
        "Negligible",
        "Inconsequential",
        "Easy",
        "Simple",
        "Straightforward",
        "Uncomplicated",
        "Effortless",
        "Painless",
        "Basic",
        "Difficult",
        "Hard",
        "Challenging",
        "Complex",
        "Complicated",
        "Tough",
        "Arduous",
        "New",
        "Fresh",
        "Modern",
        "Contemporary",
        "Current",
        "Latest",
        "Recent",
        "Old",
        "Ancient",
        "Aged",
        "Vintage",
        "Classic",
        "Traditional",
        "Old-fashioned",
        "Popular",
        "Common",
        "Widespread",
        "Universal",
        "General",
        "Standard",
        "Typical",
        "Rare",
        "Unique",
        "Uncommon",
        "Unusual",
        "Distinctive",
        "Special",
        "Exceptional",
        "Fast",
        "Quick",
        "Rapid",
        "Swift",
        "Speedy",
        "Instant",
        "Immediate",
        "Slow",
        "Gradual",
        "Leisurely",
        "Unhurried",
        "Deliberate",
        "Measured",
        "Careful",
        "Large",
        "Big",
        "Huge",
        "Massive",
        "Giant",
        "Enormous",
        "Oversized",
        "Small",
        "Tiny",
        "Mini",
        "Petite",
        "Little",
        "Bite-sized",
        "Compact",
    ],
}


def _normalize_answer_text(text: str) -> str:
    """Normalize answer text: extract first meaning, standardize formatting.

    Matches the normalization logic in QuizService to ensure consistent comparison.
    """
    if not text:
        return ""
    # Extract first meaning before semicolon
    normalized = text.split(";")[0].strip()
    # Standardize capitalization: sentence case (first letter uppercase, rest lowercase)
    if normalized:
        normalized = (
            normalized[0].upper() + normalized[1:].lower()
            if len(normalized) > 1
            else normalized.upper()
        )
    return normalized


def _load_lexicon_meanings() -> Set[str]:
    """Load all normalized term meanings from the lexicon file.

    Returns a set of normalized meanings for validation.
    """
    lexicon_path = (
        Path(__file__).parent.parent / "data" / "lexicons" / "default_lexicon.json"
    )

    if not lexicon_path.exists():
        logger.log_business_event(
            "lexicon_file_not_found",
            {"path": str(lexicon_path)},
        )
        return set()

    try:
        with open(lexicon_path, "r", encoding="utf-8") as f:
            lexicon = json.load(f)

        normalized_meanings = set()
        for item in lexicon.get("items", []):
            gloss = item.get("gloss", "")
            if gloss:
                normalized = _normalize_answer_text(gloss)
                if normalized:
                    normalized_meanings.add(normalized)

        logger.log_business_event(
            "lexicon_meanings_loaded",
            {"count": len(normalized_meanings)},
        )
        return normalized_meanings
    except Exception as e:
        logger.log_error(
            e,
            {"operation": "load_lexicon_meanings", "path": str(lexicon_path)},
        )
        return set()


def _validate_pool_against_lexicon(
    pool: List[str], category: str, lexicon_meanings: Set[str]
) -> List[str]:
    """Validate pool items against lexicon meanings.

    Returns list of pool items that match actual term meanings (should be removed).
    """
    matches = []
    for pool_item in pool:
        normalized_pool_item = _normalize_answer_text(pool_item)
        if normalized_pool_item in lexicon_meanings:
            matches.append(pool_item)
            logger.log_business_event(
                "pool_item_matches_lexicon",
                {
                    "category": category,
                    "pool_item": pool_item,
                    "normalized": normalized_pool_item,
                },
            )
    return matches


def init_quiz_pools():
    """Initialize wrong answer pools for all quiz categories.

    Validates pool items against lexicon meanings to ensure wrong answers
    don't accidentally match actual term meanings.
    """
    logger.log_business_event(
        "quiz_pools_initialization_started",
        {"total_categories": len(WRONG_ANSWER_POOLS)},
    )

    # Load lexicon meanings for validation
    lexicon_meanings = _load_lexicon_meanings()
    validation_enabled = len(lexicon_meanings) > 0

    repository = LexiconRepository()

    pools_created = 0
    pools_failed = 0
    total_warnings = 0

    for category, pool in WRONG_ANSWER_POOLS.items():
        try:
            # Validate pool items against lexicon (if available)
            validated_pool = pool.copy()
            if validation_enabled:
                matches = _validate_pool_against_lexicon(
                    pool, category.value, lexicon_meanings
                )
                if matches:
                    total_warnings += len(matches)
                    logger.log_business_event(
                        "pool_validation_warnings",
                        {
                            "category": category.value,
                            "matches_count": len(matches),
                            "matches": matches,
                        },
                    )
                    # Remove matching items from pool
                    validated_pool = [item for item in pool if item not in matches]
                    logger.log_business_event(
                        "pool_items_removed",
                        {
                            "category": category.value,
                            "removed_count": len(matches),
                            "remaining_count": len(validated_pool),
                        },
                    )

            # Only seed if we have enough pool items (need at least 10)
            if len(validated_pool) < 10:
                pools_failed += 1
                logger.log_error(
                    Exception(
                        f"Pool for {category.value} has too few items after validation: {len(validated_pool)}"
                    ),
                    {"category": category.value, "pool_size": len(validated_pool)},
                )
                continue

            success = repository.create_wrong_answer_pool(
                category.value, validated_pool
            )
            if success:
                pools_created += 1
                logger.log_business_event(
                    "wrong_answer_pool_created",
                    {
                        "category": category.value,
                        "pool_size": len(validated_pool),
                        "original_size": len(pool),
                    },
                )
            else:
                pools_failed += 1
                logger.log_error(
                    Exception(f"Failed to create pool for category: {category.value}"),
                    {"category": category.value},
                )
        except Exception as e:
            pools_failed += 1
            logger.log_error(
                e,
                {"operation": "seed_pool", "category": category.value},
            )

    logger.log_business_event(
        "quiz_pools_initialization_completed",
        {
            "pools_created": pools_created,
            "pools_failed": pools_failed,
            "total_categories": len(WRONG_ANSWER_POOLS),
            "validation_warnings": total_warnings,
            "validation_enabled": validation_enabled,
        },
    )

    return pools_created, pools_failed


if __name__ == "__main__":
    """Run the initialization when executed directly."""
    print("Starting quiz pools initialization...")

    try:
        pools_created, pools_failed = init_quiz_pools()
        print("Initialization completed successfully!")
        print(f"Pools created: {pools_created}")
        print(f"Pools failed: {pools_failed}")

        if pools_failed > 0:
            print(
                f"Warning: {pools_failed} pools failed to create. Check logs for details."
            )
            sys.exit(1)
        else:
            print("All pools initialized successfully!")
            sys.exit(0)

    except Exception as e:
        print(f"Initialization failed: {e}")
        sys.exit(1)
