# coding: utf-8

# flake8: noqa
"""
    Lingible API

    API for translating GenZ/teen slang to English and vice versa using AWS Bedrock

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


if __import__("typing").TYPE_CHECKING:
    # import models into model package
    from lingible_client.models.apple_webhook_request import AppleWebhookRequest
    from lingible_client.models.error_response import ErrorResponse
    from lingible_client.models.health_response import HealthResponse
    from lingible_client.models.pagination_info import PaginationInfo
    from lingible_client.models.success_response import SuccessResponse
    from lingible_client.models.translation_history_item_response import TranslationHistoryItemResponse
    from lingible_client.models.translation_history_response import TranslationHistoryResponse
    from lingible_client.models.translation_request import TranslationRequest
    from lingible_client.models.translation_response import TranslationResponse
    from lingible_client.models.upgrade_request import UpgradeRequest
    from lingible_client.models.upgrade_response import UpgradeResponse
    from lingible_client.models.usage_limits import UsageLimits
    from lingible_client.models.usage_response import UsageResponse
    from lingible_client.models.user_profile_response import UserProfileResponse
    from lingible_client.models.webhook_response import WebhookResponse

else:
    from lazy_imports import LazyModule, as_package, load

    load(
        LazyModule(
            *as_package(__file__),
            """# import models into model package
from lingible_client.models.apple_webhook_request import AppleWebhookRequest
from lingible_client.models.error_response import ErrorResponse
from lingible_client.models.health_response import HealthResponse
from lingible_client.models.pagination_info import PaginationInfo
from lingible_client.models.success_response import SuccessResponse
from lingible_client.models.translation_history_item_response import TranslationHistoryItemResponse
from lingible_client.models.translation_history_response import TranslationHistoryResponse
from lingible_client.models.translation_request import TranslationRequest
from lingible_client.models.translation_response import TranslationResponse
from lingible_client.models.upgrade_request import UpgradeRequest
from lingible_client.models.upgrade_response import UpgradeResponse
from lingible_client.models.usage_limits import UsageLimits
from lingible_client.models.usage_response import UsageResponse
from lingible_client.models.user_profile_response import UserProfileResponse
from lingible_client.models.webhook_response import WebhookResponse

""",
            name=__name__,
            doc=__doc__,
        )
    )
