# coding: utf-8

# flake8: noqa
"""
    Lingible API

    API for translating GenZ/teen slang to English and vice versa using AWS Bedrock

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


if __import__("typing").TYPE_CHECKING:
    # import models into model package
    from lingible_client.models.account_deletion_request import AccountDeletionRequest
    from lingible_client.models.account_deletion_response import AccountDeletionResponse
    from lingible_client.models.account_deletion_response_cleanup_summary import AccountDeletionResponseCleanupSummary
    from lingible_client.models.admin_approval_response import AdminApprovalResponse
    from lingible_client.models.apple_webhook_request import AppleWebhookRequest
    from lingible_client.models.error_response import ErrorResponse
    from lingible_client.models.health_response import HealthResponse
    from lingible_client.models.pagination_info import PaginationInfo
    from lingible_client.models.pending_submissions_response import PendingSubmissionsResponse
    from lingible_client.models.quiz_answer_request import QuizAnswerRequest
    from lingible_client.models.quiz_answer_response import QuizAnswerResponse
    from lingible_client.models.quiz_difficulty import QuizDifficulty
    from lingible_client.models.quiz_end_request import QuizEndRequest
    from lingible_client.models.quiz_history import QuizHistory
    from lingible_client.models.quiz_option import QuizOption
    from lingible_client.models.quiz_question import QuizQuestion
    from lingible_client.models.quiz_question_response import QuizQuestionResponse
    from lingible_client.models.quiz_question_result import QuizQuestionResult
    from lingible_client.models.quiz_result import QuizResult
    from lingible_client.models.quiz_session_progress import QuizSessionProgress
    from lingible_client.models.slang_submission import SlangSubmission
    from lingible_client.models.slang_submission_request import SlangSubmissionRequest
    from lingible_client.models.slang_submission_response import SlangSubmissionResponse
    from lingible_client.models.success_response import SuccessResponse
    from lingible_client.models.translation_history import TranslationHistory
    from lingible_client.models.translation_history_service_result import TranslationHistoryServiceResult
    from lingible_client.models.translation_request import TranslationRequest
    from lingible_client.models.translation_response import TranslationResponse
    from lingible_client.models.trending_list_response import TrendingListResponse
    from lingible_client.models.trending_term_response import TrendingTermResponse
    from lingible_client.models.upgrade_request import UpgradeRequest
    from lingible_client.models.upgrade_response import UpgradeResponse
    from lingible_client.models.upvote_response import UpvoteResponse
    from lingible_client.models.usage_limits import UsageLimits
    from lingible_client.models.usage_response import UsageResponse
    from lingible_client.models.user_profile_response import UserProfileResponse
    from lingible_client.models.user_subscription_response import UserSubscriptionResponse
    from lingible_client.models.webhook_response import WebhookResponse

else:
    from lazy_imports import LazyModule, as_package, load

    load(
        LazyModule(
            *as_package(__file__),
            """# import models into model package
from lingible_client.models.account_deletion_request import AccountDeletionRequest
from lingible_client.models.account_deletion_response import AccountDeletionResponse
from lingible_client.models.account_deletion_response_cleanup_summary import AccountDeletionResponseCleanupSummary
from lingible_client.models.admin_approval_response import AdminApprovalResponse
from lingible_client.models.apple_webhook_request import AppleWebhookRequest
from lingible_client.models.error_response import ErrorResponse
from lingible_client.models.health_response import HealthResponse
from lingible_client.models.pagination_info import PaginationInfo
from lingible_client.models.pending_submissions_response import PendingSubmissionsResponse
from lingible_client.models.quiz_answer_request import QuizAnswerRequest
from lingible_client.models.quiz_answer_response import QuizAnswerResponse
from lingible_client.models.quiz_difficulty import QuizDifficulty
from lingible_client.models.quiz_end_request import QuizEndRequest
from lingible_client.models.quiz_history import QuizHistory
from lingible_client.models.quiz_option import QuizOption
from lingible_client.models.quiz_question import QuizQuestion
from lingible_client.models.quiz_question_response import QuizQuestionResponse
from lingible_client.models.quiz_question_result import QuizQuestionResult
from lingible_client.models.quiz_result import QuizResult
from lingible_client.models.quiz_session_progress import QuizSessionProgress
from lingible_client.models.slang_submission import SlangSubmission
from lingible_client.models.slang_submission_request import SlangSubmissionRequest
from lingible_client.models.slang_submission_response import SlangSubmissionResponse
from lingible_client.models.success_response import SuccessResponse
from lingible_client.models.translation_history import TranslationHistory
from lingible_client.models.translation_history_service_result import TranslationHistoryServiceResult
from lingible_client.models.translation_request import TranslationRequest
from lingible_client.models.translation_response import TranslationResponse
from lingible_client.models.trending_list_response import TrendingListResponse
from lingible_client.models.trending_term_response import TrendingTermResponse
from lingible_client.models.upgrade_request import UpgradeRequest
from lingible_client.models.upgrade_response import UpgradeResponse
from lingible_client.models.upvote_response import UpvoteResponse
from lingible_client.models.usage_limits import UsageLimits
from lingible_client.models.usage_response import UsageResponse
from lingible_client.models.user_profile_response import UserProfileResponse
from lingible_client.models.user_subscription_response import UserSubscriptionResponse
from lingible_client.models.webhook_response import WebhookResponse

""",
            name=__name__,
            doc=__doc__,
        )
    )
