# coding: utf-8

"""
    Lingible API

    API for translating GenZ/teen slang to English and vice versa using AWS Bedrock

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ChallengeType(str, Enum):
    """
    Type of quiz challenge
    """

    """
    allowed enum values
    """
    MULTIPLE_CHOICE = 'multiple_choice'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ChallengeType from a JSON string"""
        return cls(json.loads(json_str))
