# coding: utf-8

"""
    Lingible API

    API for translating GenZ/teen slang to English and vice versa using AWS Bedrock

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Union
from lingible_client.models.quiz_session_progress import QuizSessionProgress
from typing import Optional, Set
from typing_extensions import Self

class QuizAnswerResponse(BaseModel):
    """
    QuizAnswerResponse
    """ # noqa: E501
    is_correct: StrictBool = Field(description="Whether the answer was correct")
    points_earned: Union[StrictFloat, StrictInt] = Field(description="Points earned for this question")
    explanation: StrictStr = Field(description="Explanation of the correct answer")
    running_stats: QuizSessionProgress
    __properties: ClassVar[List[str]] = ["is_correct", "points_earned", "explanation", "running_stats"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of QuizAnswerResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of running_stats
        if self.running_stats:
            _dict['running_stats'] = self.running_stats.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of QuizAnswerResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "is_correct": obj.get("is_correct"),
            "points_earned": obj.get("points_earned"),
            "explanation": obj.get("explanation"),
            "running_stats": QuizSessionProgress.from_dict(obj["running_stats"]) if obj.get("running_stats") is not None else None
        })
        return _obj
