# coding: utf-8

"""
    Lingible API

    API for translating GenZ/teen slang to English and vice versa using AWS Bedrock

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List
from lingible_client.models.challenge_type import ChallengeType
from lingible_client.models.quiz_challenge_scoring import QuizChallengeScoring
from lingible_client.models.quiz_difficulty import QuizDifficulty
from lingible_client.models.quiz_question import QuizQuestion
from typing import Optional, Set
from typing_extensions import Self

class QuizChallenge(BaseModel):
    """
    QuizChallenge
    """ # noqa: E501
    challenge_id: StrictStr = Field(description="Unique challenge identifier")
    challenge_type: ChallengeType
    difficulty: QuizDifficulty
    time_limit_seconds: StrictInt = Field(description="Time limit for completing the quiz")
    questions: List[QuizQuestion] = Field(description="List of quiz questions")
    scoring: QuizChallengeScoring
    expires_at: datetime = Field(description="When the challenge expires")
    __properties: ClassVar[List[str]] = ["challenge_id", "challenge_type", "difficulty", "time_limit_seconds", "questions", "scoring", "expires_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of QuizChallenge from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in questions (list)
        _items = []
        if self.questions:
            for _item_questions in self.questions:
                if _item_questions:
                    _items.append(_item_questions.to_dict())
            _dict['questions'] = _items
        # override the default output from pydantic by calling `to_dict()` of scoring
        if self.scoring:
            _dict['scoring'] = self.scoring.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of QuizChallenge from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "challenge_id": obj.get("challenge_id"),
            "challenge_type": obj.get("challenge_type"),
            "difficulty": obj.get("difficulty"),
            "time_limit_seconds": obj.get("time_limit_seconds"),
            "questions": [QuizQuestion.from_dict(_item) for _item in obj["questions"]] if obj.get("questions") is not None else None,
            "scoring": QuizChallengeScoring.from_dict(obj["scoring"]) if obj.get("scoring") is not None else None,
            "expires_at": obj.get("expires_at")
        })
        return _obj
