# coding: utf-8

"""
    Lingible API

    API for translating GenZ/teen slang to English and vice versa using AWS Bedrock

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class UpgradeRequest(BaseModel):
    """
    UpgradeRequest
    """ # noqa: E501
    platform: StrictStr = Field(description="App store platform")
    transaction_id: StrictStr = Field(description="Provider transaction ID")
    product_id: StrictStr = Field(description="Product ID from the app store")
    purchase_date: datetime = Field(description="Purchase date in ISO format")
    expiration_date: Optional[datetime] = Field(default=None, description="Expiration date in ISO format (for subscriptions)")
    environment: StrictStr = Field(description="App Store environment")
    __properties: ClassVar[List[str]] = ["platform", "transaction_id", "product_id", "purchase_date", "expiration_date", "environment"]

    @field_validator('platform')
    def platform_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['apple', 'google']):
            raise ValueError("must be one of enum values ('apple', 'google')")
        return value

    @field_validator('environment')
    def environment_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['sandbox', 'production']):
            raise ValueError("must be one of enum values ('sandbox', 'production')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpgradeRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpgradeRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "platform": obj.get("platform"),
            "transaction_id": obj.get("transaction_id"),
            "product_id": obj.get("product_id"),
            "purchase_date": obj.get("purchase_date"),
            "expiration_date": obj.get("expiration_date"),
            "environment": obj.get("environment")
        })
        return _obj
