# coding: utf-8

"""
    Lingible API

    API for translating GenZ/teen slang to English and vice versa using AWS Bedrock

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class UserSubscriptionResponse(BaseModel):
    """
    UserSubscriptionResponse
    """ # noqa: E501
    provider: Optional[StrictStr] = Field(default=None, description="Subscription provider")
    transaction_id: Optional[StrictStr] = Field(default=None, description="Provider transaction ID")
    status: Optional[StrictStr] = Field(default=None, description="Subscription status")
    start_date: Optional[datetime] = Field(default=None, description="Subscription start date")
    end_date: Optional[datetime] = Field(default=None, description="Subscription end date")
    created_at: Optional[datetime] = Field(default=None, description="Record creation date")
    __properties: ClassVar[List[str]] = ["provider", "transaction_id", "status", "start_date", "end_date", "created_at"]

    @field_validator('provider')
    def provider_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['apple', 'google']):
            raise ValueError("must be one of enum values ('apple', 'google')")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['active', 'expired', 'cancelled']):
            raise ValueError("must be one of enum values ('active', 'expired', 'cancelled')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UserSubscriptionResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UserSubscriptionResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "provider": obj.get("provider"),
            "transaction_id": obj.get("transaction_id"),
            "status": obj.get("status"),
            "start_date": obj.get("start_date"),
            "end_date": obj.get("end_date"),
            "created_at": obj.get("created_at")
        })
        return _obj
