# coding: utf-8

"""
    Lingible API

    API for translating GenZ/teen slang to English and vice versa using AWS Bedrock

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictBool, StrictStr, field_validator
from typing import Optional
from typing_extensions import Annotated
from lingible_client.models.trending_list_response import TrendingListResponse

from lingible_client.api_client import ApiClient, RequestSerialized
from lingible_client.api_response import ApiResponse
from lingible_client.rest import RESTResponseType


class TrendingApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def trending_get(
        self,
        limit: Annotated[Optional[Annotated[int, Field(le=100, strict=True, ge=1)]], Field(description="Number of trending terms to return. - Free tier: Maximum 10 terms - Premium tier: Maximum 100 terms ")] = None,
        category: Annotated[Optional[StrictStr], Field(description="Filter by trending category. - Free tier: Only 'slang' category allowed - Premium tier: All categories available ")] = None,
        active_only: Annotated[Optional[StrictBool], Field(description="Show only active trending terms")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> TrendingListResponse:
        """Get trending GenZ slang terms

        Get a list of currently trending GenZ slang terms with popularity scores and metadata.  **Free Tier Features:** - Access to top 10 trending slang terms - Basic definitions and categories - Limited to 'slang' category only  **Premium Tier Features:** - Access to up to 100 trending terms - All categories (slang, meme, expression, hashtag, phrase) - Detailed usage examples and origins - Related terms and synonyms - Search and translation counts - Advanced filtering options

        :param limit: Number of trending terms to return. - Free tier: Maximum 10 terms - Premium tier: Maximum 100 terms
        :type limit: int
        :param category: Filter by trending category. - Free tier: Only 'slang' category allowed - Premium tier: All categories available
        :type category: str
        :param active_only: Show only active trending terms
        :type active_only: bool
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._trending_get_serialize(
            limit=limit,
            category=category,
            active_only=active_only,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "TrendingListResponse",
            '401': "ErrorResponse",
            '400': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def trending_get_with_http_info(
        self,
        limit: Annotated[Optional[Annotated[int, Field(le=100, strict=True, ge=1)]], Field(description="Number of trending terms to return. - Free tier: Maximum 10 terms - Premium tier: Maximum 100 terms ")] = None,
        category: Annotated[Optional[StrictStr], Field(description="Filter by trending category. - Free tier: Only 'slang' category allowed - Premium tier: All categories available ")] = None,
        active_only: Annotated[Optional[StrictBool], Field(description="Show only active trending terms")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[TrendingListResponse]:
        """Get trending GenZ slang terms

        Get a list of currently trending GenZ slang terms with popularity scores and metadata.  **Free Tier Features:** - Access to top 10 trending slang terms - Basic definitions and categories - Limited to 'slang' category only  **Premium Tier Features:** - Access to up to 100 trending terms - All categories (slang, meme, expression, hashtag, phrase) - Detailed usage examples and origins - Related terms and synonyms - Search and translation counts - Advanced filtering options

        :param limit: Number of trending terms to return. - Free tier: Maximum 10 terms - Premium tier: Maximum 100 terms
        :type limit: int
        :param category: Filter by trending category. - Free tier: Only 'slang' category allowed - Premium tier: All categories available
        :type category: str
        :param active_only: Show only active trending terms
        :type active_only: bool
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._trending_get_serialize(
            limit=limit,
            category=category,
            active_only=active_only,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "TrendingListResponse",
            '401': "ErrorResponse",
            '400': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def trending_get_without_preload_content(
        self,
        limit: Annotated[Optional[Annotated[int, Field(le=100, strict=True, ge=1)]], Field(description="Number of trending terms to return. - Free tier: Maximum 10 terms - Premium tier: Maximum 100 terms ")] = None,
        category: Annotated[Optional[StrictStr], Field(description="Filter by trending category. - Free tier: Only 'slang' category allowed - Premium tier: All categories available ")] = None,
        active_only: Annotated[Optional[StrictBool], Field(description="Show only active trending terms")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get trending GenZ slang terms

        Get a list of currently trending GenZ slang terms with popularity scores and metadata.  **Free Tier Features:** - Access to top 10 trending slang terms - Basic definitions and categories - Limited to 'slang' category only  **Premium Tier Features:** - Access to up to 100 trending terms - All categories (slang, meme, expression, hashtag, phrase) - Detailed usage examples and origins - Related terms and synonyms - Search and translation counts - Advanced filtering options

        :param limit: Number of trending terms to return. - Free tier: Maximum 10 terms - Premium tier: Maximum 100 terms
        :type limit: int
        :param category: Filter by trending category. - Free tier: Only 'slang' category allowed - Premium tier: All categories available
        :type category: str
        :param active_only: Show only active trending terms
        :type active_only: bool
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._trending_get_serialize(
            limit=limit,
            category=category,
            active_only=active_only,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "TrendingListResponse",
            '401': "ErrorResponse",
            '400': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _trending_get_serialize(
        self,
        limit,
        category,
        active_only,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if limit is not None:

            _query_params.append(('limit', limit))

        if category is not None:

            _query_params.append(('category', category))

        if active_only is not None:

            _query_params.append(('active_only', active_only))

        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'BearerAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/trending',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )
