# coding: utf-8

# flake8: noqa

"""
    Lingible API

    API for translating GenZ/teen slang to English and vice versa using AWS Bedrock

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "SystemApi",
    "TranslationApi",
    "TrendingApi",
    "UserApi",
    "WebhooksApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AccountDeletionRequest",
    "AccountDeletionResponse",
    "AccountDeletionResponseCleanupSummary",
    "AppleWebhookRequest",
    "ErrorResponse",
    "HealthResponse",
    "PaginationInfo",
    "ReceiptValidationResponse",
    "SuccessResponse",
    "TranslationHistoryItemResponse",
    "TranslationHistoryResponse",
    "TranslationRequest",
    "TranslationResponse",
    "TrendingListResponse",
    "TrendingTermResponse",
    "UpgradeRequest",
    "UpgradeResponse",
    "UsageLimits",
    "UsageResponse",
    "UserProfileResponse",
    "UserSubscriptionResponse",
    "WebhookResponse",
]

if __import__("typing").TYPE_CHECKING:
    # import apis into sdk package
    from lingible_client.api.system_api import SystemApi as SystemApi
    from lingible_client.api.translation_api import TranslationApi as TranslationApi
    from lingible_client.api.trending_api import TrendingApi as TrendingApi
    from lingible_client.api.user_api import UserApi as UserApi
    from lingible_client.api.webhooks_api import WebhooksApi as WebhooksApi

    # import ApiClient
    from lingible_client.api_response import ApiResponse as ApiResponse
    from lingible_client.api_client import ApiClient as ApiClient
    from lingible_client.configuration import Configuration as Configuration
    from lingible_client.exceptions import OpenApiException as OpenApiException
    from lingible_client.exceptions import ApiTypeError as ApiTypeError
    from lingible_client.exceptions import ApiValueError as ApiValueError
    from lingible_client.exceptions import ApiKeyError as ApiKeyError
    from lingible_client.exceptions import ApiAttributeError as ApiAttributeError
    from lingible_client.exceptions import ApiException as ApiException

    # import models into sdk package
    from lingible_client.models.account_deletion_request import AccountDeletionRequest as AccountDeletionRequest
    from lingible_client.models.account_deletion_response import AccountDeletionResponse as AccountDeletionResponse
    from lingible_client.models.account_deletion_response_cleanup_summary import AccountDeletionResponseCleanupSummary as AccountDeletionResponseCleanupSummary
    from lingible_client.models.apple_webhook_request import AppleWebhookRequest as AppleWebhookRequest
    from lingible_client.models.error_response import ErrorResponse as ErrorResponse
    from lingible_client.models.health_response import HealthResponse as HealthResponse
    from lingible_client.models.pagination_info import PaginationInfo as PaginationInfo
    from lingible_client.models.receipt_validation_response import ReceiptValidationResponse as ReceiptValidationResponse
    from lingible_client.models.success_response import SuccessResponse as SuccessResponse
    from lingible_client.models.translation_history_item_response import TranslationHistoryItemResponse as TranslationHistoryItemResponse
    from lingible_client.models.translation_history_response import TranslationHistoryResponse as TranslationHistoryResponse
    from lingible_client.models.translation_request import TranslationRequest as TranslationRequest
    from lingible_client.models.translation_response import TranslationResponse as TranslationResponse
    from lingible_client.models.trending_list_response import TrendingListResponse as TrendingListResponse
    from lingible_client.models.trending_term_response import TrendingTermResponse as TrendingTermResponse
    from lingible_client.models.upgrade_request import UpgradeRequest as UpgradeRequest
    from lingible_client.models.upgrade_response import UpgradeResponse as UpgradeResponse
    from lingible_client.models.usage_limits import UsageLimits as UsageLimits
    from lingible_client.models.usage_response import UsageResponse as UsageResponse
    from lingible_client.models.user_profile_response import UserProfileResponse as UserProfileResponse
    from lingible_client.models.user_subscription_response import UserSubscriptionResponse as UserSubscriptionResponse
    from lingible_client.models.webhook_response import WebhookResponse as WebhookResponse

else:
    from lazy_imports import LazyModule, as_package, load

    load(
        LazyModule(
            *as_package(__file__),
            ("__version__", __version__),
            ("__all__", __all__),
            """# import apis into sdk package
from lingible_client.api.system_api import SystemApi as SystemApi
from lingible_client.api.translation_api import TranslationApi as TranslationApi
from lingible_client.api.trending_api import TrendingApi as TrendingApi
from lingible_client.api.user_api import UserApi as UserApi
from lingible_client.api.webhooks_api import WebhooksApi as WebhooksApi

# import ApiClient
from lingible_client.api_response import ApiResponse as ApiResponse
from lingible_client.api_client import ApiClient as ApiClient
from lingible_client.configuration import Configuration as Configuration
from lingible_client.exceptions import OpenApiException as OpenApiException
from lingible_client.exceptions import ApiTypeError as ApiTypeError
from lingible_client.exceptions import ApiValueError as ApiValueError
from lingible_client.exceptions import ApiKeyError as ApiKeyError
from lingible_client.exceptions import ApiAttributeError as ApiAttributeError
from lingible_client.exceptions import ApiException as ApiException

# import models into sdk package
from lingible_client.models.account_deletion_request import AccountDeletionRequest as AccountDeletionRequest
from lingible_client.models.account_deletion_response import AccountDeletionResponse as AccountDeletionResponse
from lingible_client.models.account_deletion_response_cleanup_summary import AccountDeletionResponseCleanupSummary as AccountDeletionResponseCleanupSummary
from lingible_client.models.apple_webhook_request import AppleWebhookRequest as AppleWebhookRequest
from lingible_client.models.error_response import ErrorResponse as ErrorResponse
from lingible_client.models.health_response import HealthResponse as HealthResponse
from lingible_client.models.pagination_info import PaginationInfo as PaginationInfo
from lingible_client.models.receipt_validation_response import ReceiptValidationResponse as ReceiptValidationResponse
from lingible_client.models.success_response import SuccessResponse as SuccessResponse
from lingible_client.models.translation_history_item_response import TranslationHistoryItemResponse as TranslationHistoryItemResponse
from lingible_client.models.translation_history_response import TranslationHistoryResponse as TranslationHistoryResponse
from lingible_client.models.translation_request import TranslationRequest as TranslationRequest
from lingible_client.models.translation_response import TranslationResponse as TranslationResponse
from lingible_client.models.trending_list_response import TrendingListResponse as TrendingListResponse
from lingible_client.models.trending_term_response import TrendingTermResponse as TrendingTermResponse
from lingible_client.models.upgrade_request import UpgradeRequest as UpgradeRequest
from lingible_client.models.upgrade_response import UpgradeResponse as UpgradeResponse
from lingible_client.models.usage_limits import UsageLimits as UsageLimits
from lingible_client.models.usage_response import UsageResponse as UsageResponse
from lingible_client.models.user_profile_response import UserProfileResponse as UserProfileResponse
from lingible_client.models.user_subscription_response import UserSubscriptionResponse as UserSubscriptionResponse
from lingible_client.models.webhook_response import WebhookResponse as WebhookResponse

""",
            name=__name__,
            doc=__doc__,
        )
    )
